archives:
- format: tar.gz
  format_overrides:
  - format: zip
    goos: windows
  name_template: '{{ .ProjectName }}_ {{- title .Os }}_ {{- if eq .Arch "amd64" }}x86_64
    {{- else if eq .Arch "386" }}i386 {{- else }}{{ .Arch }}{{ end }} {{- if .Arm
    }}v{{ .Arm }}{{ end }}'
before:
  hooks:
  - go mod tidy
  - go test -count=1 -v ./...
builds:
- binary: cluster-lifecycle
  env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - linux
  id: cluster-lifecycle
  ldflags:
  - -s -w -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.version={{.Version}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.commit={{.Commit}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.date={{.Date}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.builtBy=goreleaser
  main: ./cmd/cluster-lifecycle
- binary: mco-builder
  env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - linux
  id: mco-builder
  ldflags:
  - -s -w -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.version={{.Version}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.commit={{.Commit}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.date={{.Date}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.builtBy=goreleaser
  main: ./cmd/mco-builder
- binary: mco-push
  env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - linux
  id: mco-push
  ldflags:
  - -s -w -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.version={{.Version}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.commit={{.Commit}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.date={{.Date}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.builtBy=goreleaser
  main: ./cmd/mco-push
- binary: onclustertesting
  env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - linux
  id: onclustertesting
  ldflags:
  - -s -w -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.version={{.Version}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.commit={{.Commit}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.date={{.Date}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.builtBy=goreleaser
  main: ./cmd/onclustertesting
- binary: run-on-all-nodes
  env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - linux
  id: run-on-all-nodes
  ldflags:
  - -s -w -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.version={{.Version}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.commit={{.Commit}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.date={{.Date}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.builtBy=goreleaser
  main: ./cmd/run-on-all-nodes
- binary: wait-for-mcp
  env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - linux
  id: wait-for-mcp
  ldflags:
  - -s -w -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.version={{.Version}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.commit={{.Commit}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.date={{.Date}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.builtBy=goreleaser
  main: ./cmd/wait-for-mcp
changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
  sort: asc
checksum:
  name_template: checksums.txt
snapshot:
  name_template: '{{ incpatch .Version }}-next'
