archives:
- format: tar.gz
  format_overrides:
  - format: zip
    goos: windows
  name_template: '{{ .ProjectName }}_ {{- title .Os }}_ {{- if eq .Arch "amd64" }}x86_64
    {{- else if eq .Arch "386" }}i386 {{- else }}{{ .Arch }}{{ end }} {{- if .Arm
    }}v{{ .Arm }}{{ end }}'
before:
  hooks:
  - go mod tidy
  - go test -count=1 -v ./...
builds:
- binary: cluster-lifecycle
  env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - linux
  id: cluster-lifecycle
  ldflags:
  - -s -w -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.version={{.Version}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.commit={{.Commit}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.date={{.Date}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.builtBy=goreleaser
  main: ./cmd/cluster-lifecycle
- binary: mco-builder
  env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - linux
  id: mco-builder
  ldflags:
  - -s -w -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.version={{.Version}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.commit={{.Commit}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.date={{.Date}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.builtBy=goreleaser
  main: ./cmd/mco-builder
- binary: mco-push
  env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - linux
  id: mco-push
  ldflags:
  - -s -w -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.version={{.Version}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.commit={{.Commit}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.date={{.Date}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.builtBy=goreleaser
  main: ./cmd/mco-push
- binary: onclustertesting
  env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - linux
  id: onclustertesting
  ldflags:
  - -s -w -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.version={{.Version}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.commit={{.Commit}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.date={{.Date}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.builtBy=goreleaser
  main: ./cmd/onclustertesting
- binary: run-on-all-nodes
  env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - linux
  id: run-on-all-nodes
  ldflags:
  - -s -w -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.version={{.Version}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.commit={{.Commit}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.date={{.Date}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.builtBy=goreleaser
  main: ./cmd/run-on-all-nodes
- binary: wait-for-mcp
  env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - linux
  id: wait-for-mcp
  ldflags:
  - -s -w -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.version={{.Version}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.commit={{.Commit}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.date={{.Date}}
    -X github.com/cheesesashimi/zacks-openshift-helpers/internal/pkg/version.builtBy=goreleaser
  main: ./cmd/wait-for-mcp
changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
  sort: asc
checksum:
  name_template: checksums.txt
docker_manifests:
- image_templates:
  - quay.io/zzlotnik/{{ .ProjectName }}:{{ .Version }}-amd64
  - quay.io/zzlotnik/{{ .ProjectName }}:{{ .Version }}-arm64
  name_template: quay.io/zzlotnik/{{ .ProjectName }}:{{ .Version }}
- image_templates:
  - quay.io/zzlotnik/{{ .ProjectName }}:{{ .Version }}-amd64
  - quay.io/zzlotnik/{{ .ProjectName }}:{{ .Version }}-arm64
  name_template: quay.io/zzlotnik/{{ .ProjectName }}:latest
dockers:
- build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/cheesesashimi/{{ .ProjectName
    }}
  - --label=org.opencontainers.image.source=https://github.com/cheesesashimi/{{ .ProjectName
    }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - '{{ if index .Env "GITHUB_ACTIONS" }}--label=com.github.actions={{else}}--label={{end}}'
  - '{{ if index .Env "GITHUB_RUN_ID" }}--label=com.github.actions.runId={{ .Env.GITHUB_RUN_ID
    }}{{else}}--label={{end}}'
  - '{{ if index .Env "GITHUB_RUN_NUMBER" }}--label=com.github.actions.runNumber={{
    .Env.GITHUB_RUN_NUMBER }}{{else}}--label={{end}}'
  - '{{ if index .Env "GITHUB_WORKFLOW" }}--label=com.github.actions.workflow={{ .Env.GITHUB_WORKFLOW
    }}{{else}}--label={{end}}'
  - '{{ if index .Env "RUNNER_NAME" }}--label=com.github.actions.runnerName={{ .Env.RUNNER_NAME
    }}{{else}}--label={{end}}'
  dockerfile: Dockerfile.goreleaser
  goarch: amd64
  goos: linux
  ids:
  - cluster-lifecycle
  - mco-builder
  - mco-push
  - onclustertesting
  - run-on-all-nodes
  - wait-for-mcp
  image_templates:
  - quay.io/zzlotnik/{{ .ProjectName }}:{{ .Version }}-amd64
- build_flag_templates:
  - --platform=linux/arm64
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/cheesesashimi/{{ .ProjectName
    }}
  - --label=org.opencontainers.image.source=https://github.com/cheesesashimi/{{ .ProjectName
    }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - '{{ if index .Env "GITHUB_ACTIONS" }}--label=com.github.actions={{else}}--label={{end}}'
  - '{{ if index .Env "GITHUB_RUN_ID" }}--label=com.github.actions.runId={{ .Env.GITHUB_RUN_ID
    }}{{else}}--label={{end}}'
  - '{{ if index .Env "GITHUB_RUN_NUMBER" }}--label=com.github.actions.runNumber={{
    .Env.GITHUB_RUN_NUMBER }}{{else}}--label={{end}}'
  - '{{ if index .Env "GITHUB_WORKFLOW" }}--label=com.github.actions.workflow={{ .Env.GITHUB_WORKFLOW
    }}{{else}}--label={{end}}'
  - '{{ if index .Env "RUNNER_NAME" }}--label=com.github.actions.runnerName={{ .Env.RUNNER_NAME
    }}{{else}}--label={{end}}'
  dockerfile: Dockerfile.goreleaser
  goarch: arm64
  goos: linux
  ids:
  - cluster-lifecycle
  - mco-builder
  - mco-push
  - onclustertesting
  - run-on-all-nodes
  - wait-for-mcp
  image_templates:
  - quay.io/zzlotnik/{{ .ProjectName }}:{{ .Version }}-arm64
snapshot:
  name_template: '{{ incpatch .Version }}-next'
